# Generated by Django 3.1 on 2020-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_msg_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
