# Generated by Django 3.1 on 2020-08-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='msgs.thread'),
        ),
    ]
